### ISSUE TITLE
Code snippet for cleaning the data

### ISSUE THREAD

**Issue by kumarama3** [bharathprabakaran/FPUS23#1]
Hi,

Are there any steps for cleaning the data and loading it. It would be very helpful.

I am trying to build object detection model . which images(in folder) are generally considered

**Comment by bharathprabakaran** [comment]
The source codes for loading and/or training the models have been pushed to the repo in a recent commit. Please pull the latest version for the same.

**Comment by kumarama3** [comment]
Thank you very much !
