### ISSUE TITLE
Regarding training yolo model

### ISSUE THREAD

**Issue by kumarama3** [bharathprabakaran/FPUS23#2]
Hi,

I am planning to train yolo model.. Can you suggest which model can I use as backbone for training separately.
Can you also provide code for training classification model used in the paper .It would be very helpful

Thank you very much

**Comment by bharathprabakaran** [comment]
Hello,

The [paper](https://ieeexplore.ieee.org/document/10146252/) discusses the use of ResNet34 and ResNet10 backbones for object detection. The codes for the same are already in the repository, OD folder.

**Comment by kumarama3** [comment]
> Hello,
> 
> The [paper](https://ieeexplore.ieee.org/document/10146252/) discusses the use of ResNet34 and ResNet10 backbones for object detection. The codes for the same are already in the repository, OD folder.

Hi, 

Thanks for your reply.

In the repo, I observe that the code contains object detection model trained end to end using resnet 10 /34 model. But I am looking for separate classification model trained on the dataset.

Thank you

**Comment by bharathprabakaran** [comment]
The repo also contains source codes for training classifiers on the orientation and plane information. Perhaps you could look into that. Anything else would have to be manually adapted at your end, which should be quite straight-forward given the dataset.
